### ISSUE TITLE
[faceted search] Set filters from route query params (all-products)

### ISSUE THREAD

**Issue by agritheory** [agritheory/inventory_tools#112]

**Comment by Alchez** [comment]
@agritheory This already seems to be [happening](https://github.com/agritheory/inventory_tools/blob/version-15/inventory_tools/public/js/faceted_search/FacetedSearch.vue#L93-L113) (to an extent) in both the website and listview.

Here's the pending issues I'm seeing here:
- [x] If a URL with pre-existing query params is loaded, the view _applies_ the filters correctly but doesn't currently show them in the view.
  - This should be fairly trivial to solve since we can initialize values for attribute components.
- [x] If a user manually adds a filter via the sidebar, the URL is not updated with the relevant query params.
  - I was able to solve this with the VueUse composable, however the URL format needs to be consistent with what the existing code expects (url-encoded? json-stringified? etc.).

I'll wait for your thoughts before I start working on this in case I'm missing something else as well.

**Comment by agritheory** [comment]
This are the same symptoms that I was seeing. I don't have a strong opinion about what encoding should be used
