### ISSUE TITLE
Tests for Material Demand workflow

### ISSUE THREAD

**Issue by agritheory** [agritheory/inventory_tools#17]
Should test both a single company approach (defined by settings) and a multi-company one, which requires a bunch more fixtures. 

Also, documentation.

**Comment by federicocalvo** [comment]
### Issue:

Following the documentation, in the case of having more than one company, and configured as mentioned above, the creation of a multi-company PO still forces us to choose one.

To reproduce the issue:

-Configuration, for two settings inventory tools like that:

![Captura de pantalla 2024-02-07 a la(s) 10 34 47](https://github.com/agritheory/inventory_tools/assets/7256766/75e4c8f2-eefb-4d59-ae8b-b2e5d2cdf0f5)

-Create two MRQ with de same item but diferent companys.

-Create de PO in the Material Demand Report for that item:

![Captura de pantalla 2024-02-07 a la(s) 10 35 18](https://github.com/agritheory/inventory_tools/assets/7256766/a6fd350a-ae1c-42c5-af00-543bf97b45fb)

- See the dialog:
![Captura de pantalla 2024-02-07 a la(s) 10 35 29](https://github.com/agritheory/inventory_tools/assets/7256766/4affe116-0dc7-41a0-b650-643fcbb0848c)

**Comment by agritheory** [comment]
@federicocalvo This could be a bug, but I can also imagine a user story where it makes sense. That _usually_ means the documentation is not clear enough, though I think the "select a company" message here is also probably not clear enough.

1. The user wants to aggregate MRs across companies and both the company and warehouse are set so that purchasing is executed by the designated company, resulting in one PO or RFQ per supplier. 
2. The user wants to aggregate all the MRs but hasn't set the Company filter in the report. In this case, we either need to know which company to aggregate to (I think this path is a bug and shouldn't be allowed) OR we should aggregate based on the requesting company and create PO/ RFQ on a per-company, per-supplier basis.
3. The user wants to aggregate the MRs but on per-company-basis and has not set the company filter in the report. In this case I don't think the selection dialog needs to be shown.

**Comment by federicocalvo** [comment]
@agritheory To make clear what we should modify having in mind the sense of the use cases.

- [ ]  If more than one company is used, the Purchase Order Aggregation Company configuration does not make sense, we should remove it.

- [ ]  Make the change to ensure that if there is more than one company, run the RFQ/PO per company per supplier automatically.

- [ ]  This way it also pulls up the popups where it chooses the company.

- [ ] Correct the material_demand.md

**Comment by agritheory** [comment]
> If more than one company is used, the Purchase Order Aggregation Company configuration does not make sense, we should remove it. 

The idea is that in a family of companies, one might be responsible for purchasing all the materials on behalf of the others. If the Purchase Order Aggregation Company and Purchase Order Aggregation Warehouse are not set in Inventory Tools Settings, the user does not want to use this workflow.

**Comment by federicocalvo** [comment]
@agritheory Leaving in clean because of the misunderstanding of the previous comment. What I saw is the following:

> The idea is that in a family of companies, one might be responsible for purchasing all the materials on behalf of the others. If the Purchase Order Aggregation Company and Purchase Order Aggregation Warehouse are not set in Inventory Tools Settings, the user does not want to use this workflow.

The behavior that one sets in the configuration, is because it is always for that way, then this does not consult us on which company or which warehouse if they have configured. But they are not the only expected behaviors.

In order for both behaviors to be performed, that we select MR from different companies, creating it separately from each company, and that we select Material Request from different companies, and they can be performed on behalf of one, 

- [ ] we need to resolve it in the popup that the company selection is not mandatory. Then if the company field is left blank, the RFQ or PO is made for each one taking the configuration that each one has. We should add a helptext clarifying this. 

- [ ] In case of selecting a company, both RFQs will be made on name of this company.
Here we also have to solve the error that does not know from where to take the warehouse of the company that was discarded, to add one that has the chosen one. The most logical and simple thing would be to take from the configuration of the item default_warehouse. This has nothing to do with the configuration where we can choose a warehouse to overwrite what is in the MR.

- [ ] Then, modify de docs

**Comment by federicocalvo** [comment]
@agritheory I went over this again and again, and now I understand that it was quite difficult, because the documentation said one thing, and then the operation was different, or had certain problems, which made me doubt if I was understanding correctly.

I had to appeal to Francisco to not only transmit the same thing that I told you in the call, but also to review the code.

There we found, among other things, that it was not designed for multi-company transactions. 

Then, Francisco told me from his perspective of test use, that configuring the behavior in each company to automatically generate a multi-company PO is confusing, let alone if you have more than two company.

We reviewed the call to remember why you did not agree with doing it in this way, and it is not very clear, so we took the boldness without much effort, to make this PR, because it is incredibly simple, understandable (much easier to explain in the documentation), and of course we corrected errors of being able to choose any warehouse, to really place the multicompany checkbox in PO, etc. The same for RFQ.

![issue](https://github.com/agritheory/inventory_tools/assets/7256766/112d0ef7-5adf-4e81-a1e6-62df5e419d94)

![Captura de pantalla 2024-03-01 a la(s) 09 57 51](https://github.com/agritheory/inventory_tools/assets/7256766/028458f0-2d0b-486f-a2c8-13fff471bd55)
