### ISSUE TITLE
Version 15 release

### ISSUE THREAD

**Issue by agritheory** [agritheory/inventory_tools#78]
Update release.yaml to be compatible with both 14 and 15 branches

Job Card submit in setup.py need some attention,
Integrate Plant Floor feature

**Comment by MyuddinKhatri** [comment]
@agritheory for `Integrate Plant Floor feature` not sure about this, do we want to merge branch `add_plant_floor` into version-15?

**Comment by agritheory** [comment]
@MyuddinKhatri No, it's not ready yet

**Comment by MyuddinKhatri** [comment]
@agritheory As we already have #83 can we track `Use test_utils dependency` from this ticket in the mentioned ticket. And as you said Plant Floor feature is not ready yet, create a separate ticket to track this, so this PR - #97 becomes ready for review?

**Comment by agritheory** [comment]
@MyuddinKhatri No, I think the tests related to Job Cards are still failing in V15, this can't be closed until that's resolved.

**Comment by HKuz** [comment]
Hi all,

@agritheory asked me to share how to get the `version-15` branch's semantic versioning numbering to work so it uses "v15.x.x" instead of "v14.x.x". 

In general, once the `release.yaml` workflow has the version-15 branch in there, it will look through the git commit history for any tags attached to commits that match the "v{version}" pattern (note that the "v" is lowercase and the {version} part follows the MAJOR.MINOR.PATCH numbering format). It will increment the latest number based on the last one found in the history. Since `version-15` branched off `version-14`, it has all those tags in its history. In order to get it to start numbering off a "v15.0.0", we need to manually create a release/tag in GitHub targeting the `version-15` branch. Since this doesn't exist yet, when the release workflow updated to include the `version-15` branch, Python Semantic Release only found "v14.x.x" tags in its history, so it kept incrementing that.

## How to Create a Tag/Release
- Click over to the Releases section (you can find a link to it in the right-hand sidebar when on the repo's "home" screen)
- Click "Draft a New Release"
    - In the "Choose a Tag" section, type a new tag v15.0.0 (the "v" needs to be lowercase) and click the "Create new tag v15.0.0 on publish" option
    - Set the target branch to `version-15`
    - I've never used the "generate release notes" feature, may want to see what it generates
    - Can title the release as something like "Initial Version-15 Release"
    - Uncheck the options for pre-release and the latest release (latest should stay as the latest v14.x.x one since v15 isn't done yet)
    - Publish the release
    - Note: new tags always attach to the latest commit
- Optional: clean up the `version-15` branch's CHANGELOG.md file by deleting those old v14.x.x version notes (basically clearing the file after the "CHANGELOG" title). The version showing in the `__init__.py` file will update automatically once releases are on
- When ready, add the `version-15` branch to the `release.yaml` file
